<?php

namespace AppBundle\Repository;

/**
 * CamposAfines
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamposAfines extends \Doctrine\ORM\EntityRepository
{
}
