<?php

namespace AppBundle\Repository;

/**
 * estatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estatusRepository extends \Doctrine\ORM\EntityRepository
{
}
