<?php

namespace AppBundle\Repository;

/**
 * solicitud_notasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solicitud_notasRepository extends \Doctrine\ORM\EntityRepository
{
}
