<?php

namespace AppBundle\Repository;

/**
 * UsuarioCamposAfinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCamposAfinesRepository extends \Doctrine\ORM\EntityRepository
{
}
