<?php

namespace AppBundle\Repository;

/**
 * usuario_campos_afinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuario_campos_afinRepository extends \Doctrine\ORM\EntityRepository
{
}
